pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws-access-key')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
        TF_VERSION = "1.6.6"
    }

    stages {

        stage('Clone SCM') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Harinath234/Project_10_Eks_Cluster_with_terraform.git'
            }
        }

        stage('Install Terraform') {
            steps {
                sh '''
                if [ ! -f "$WORKSPACE/bin/terraform" ]; then
                    mkdir -p $WORKSPACE/bin

                    curl -LO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip

                    unzip -o terraform_${TF_VERSION}_linux_amd64.zip

                    mv terraform $WORKSPACE/bin/

                    chmod +x $WORKSPACE/bin/terraform
                fi

                export PATH=$WORKSPACE/bin:$PATH

                terraform --version
                '''
            }
        }

        stage('Terraform Init') {
            steps {
                sh '''
                export PATH=$WORKSPACE/bin:$PATH

                cd eks-install

                terraform init
                '''
            }
        }

        stage('Terraform Validate') {
            steps {
                sh '''
                export PATH=$WORKSPACE/bin:$PATH

                cd eks-install

                terraform validate
                '''
            }
        }

        stage('Terraform Plan') {
            steps {
                sh '''
                export PATH=$WORKSPACE/bin:$PATH

                cd eks-install

                terraform plan -out=tfplan
                '''
            }
        }

        stage('Terraform Apply') {
            steps {
                sh '''
                export PATH=$WORKSPACE/bin:$PATH

                cd eks-install

                terraform apply -auto-approve tfplan
             // terraform destroy -auto-approve
                '''
            }
        }
    }

    post {
        success {
            echo 'Terraform deployment completed successfully!'
        }

        failure {
            echo 'Terraform deployment failed. Check logs.'
        }

        always {
            deleteDir()
        }
    }
}
